### PR TITLE
Feature/scripts

### PR DESCRIPTION
**Pull request by JBurlison**
Master compare

### CODE REVIEW

**Comment by Fabi** [comment]
What exactly is the intention here? Implement missing things in Cypher that are already in TC?

If so, split everything in smaller PRs so we can track it on TC please. We won't be able to merge it like that.

**Comment by JBurlison** [comment]
This is an optimization to the spell script system to make it more generic, since it changes the underlying system, it touches every script.

I cannot make it smaller.

**Comment by Fabi** [comment]
> This is an optimization to the spell script system to make it more generic, since it changes the underlying system, it touches every script.
> 
> I cannot make it smaller.

It contains many other random things that got nothing to do with the spell script system itself.

**Comment by JBurlison** [comment]
I am adding the aura script overhaul shortly also

**Comment by JBurlison** [comment]
Yes, contains:

- crash fixes
- optimization of the spell script system
- optimization of the aura script system
- Support for char_base_info db
- Several new Configuration options for people who want to tweak the level range of the server without having to have it hard coded everywhere.

**Comment by Fabi** [comment]
> Yes, contains:
> 
> * crash fixes
> * optimization of the spell script system
> * optimization of the aura script system
> * Support for char_base_info db
> * Several new Configuration options for people who want to tweak the level range of the server without having to have it hard coded everywhere.

too much in one. split them to a possible minimum please

**Comment by ZaDarkSide** [comment]
Yeah at least make separate pull requests with each category of fix, for each crash fix make a separate pull request, for each new feature or new config option make a separate pull request, and well for the spell / aura system overhaul I understand that is difficult to split into many pull requests so maybe you will keep it into a single pull request, but for sure the others can be split in different pull requests.

**Comment by JBurlison** [comment]
I mean the PR is a curtesy, you can take it or leave it but I did this because im currently moving a ton of scripts over from a private repack, before I do Im optimizing the core.

If you dont want it just close the PR and Ill just continue on with my own version of Cypher

**Comment by JBurlison** [comment]
oh warlock pets where added too that I did for testing these changes

**Comment by ZaDarkSide** [comment]
> I mean the PR is a curtesy, you can take it or leave it but I did this because im currently moving a ton of scripts over from a private repack, before I do Im optimizing the core.
> 
> If you dont want it just close the PR and Ill just continue on with my own version of Cypher
>  

We appreciate any contribution, but like any open source project there are some rules on how you can contribute efficiently to make sure your PR is accepted.

Usually smaller PRs are tested and reviewed more easily by all the people involved in the project, nobody can look at possibly hundreds of lines of code in 20+ commits in a single PR, that's why you were asked to split it in smaller chunks.

Hopefully you understand this position and this will not deter you in the future from contributing to the project while following the rules explained so far.

Thank you again for trying. 👍

**Comment by JBurlison** [comment]
https://github.com/ForgedWoW/CypherCore/blob/master/Source/Game/Scripting/ScriptManager.cs#L1303
ok so things like this
this is bad
so ToList() enumerates over the values to create it
https://github.com/ForgedWoW/CypherCore/blob/master/Source/Game/Scripting/ScriptManager.cs#L1172
Then here, using that to loop over all the scripts
so double loop
can cut the call time in half just by changing GetStorage to
```
    public IEnumerable<ScriptObject> GetStorage()
        {
            return _scriptMap.Values;
        }
```
another performance boost is that this is called for every script interface thing 
`public void ForEach<T>(Action<T> a) where T : ScriptObject `
so this needs to be streamlined a bit too
im going to optimize this by only calling this for the scripts that only care about what is being invoked, simmilar on how i did the spell and aura system
extract calls to interfaces
https://github.com/ForgedWoW/CypherCore/blob/master/Source/Game/Scripting/ScriptManager.cs#L1034
like all thse
because what ends up happening here is every step of the script API for a object like map or player looks over every script for every API call to that script even if the script does not use that Api method
so im going to do a bunch of interface extraction
and make it so when you invoke the script manager, you can tell it the specifc call you are doing
and it will only loop the scripts that care about that call
the performance increase will be like  20 fold
100's of times more performant
as each of these redundant loops are removed from the call stack
it gets expedientially faster

Like I understand this is a big PR but, the bigger picture here is the code that is there is a direct translation from c++ and is not performant in c# 

I am re-writting the script manager now Ill put a PR in for that too but again its going to touch 100s of classes  because of the changes.

**Comment by JBurlison** [comment]
Ill leave this because I have every zone script and spell coming in the future and you will need this if you want them for the core.

**Comment by Fabi** [comment]
Try to prevent usage of IEnumerable/Enumerable whenever it's possible. It's one of the worst interfaces/classes to use performance wise too. Use something else there.

**Pull request closed without merging**
