### PR TITLE
Fix Parsing floats and double

### PR DESCRIPTION
**Pull request by kostyatab**

### CODE REVIEW

**Comment by Fabi** [comment]
This should already be fixed with a previous commit?!

https://github.com/CypherCore/CypherCore/commit/ff15083cfebba7a131600c3be2e8642ca9db916a#diff-836d92384a7e8a9de3adc0e31cce12e8

**Comment by kostyatab** [comment]
This commit does't fix error

**Comment by Fabi** [comment]
Can you give me an example where it's not working

**Comment by kostyatab** [comment]
local culture: ru-RU

**Comment by hondacrx** [comment]
Should be fixed in https://github.com/CypherCore/CypherCore/commit/8b43b08f6f1110249034ad982504ebdd0b685189

**Pull request closed without merging**
