### PR TITLE
Core: Updated allowed build to 10.0.5.48069 from TC

### PR DESCRIPTION
**Pull request by HerokDeV**

### CODE REVIEW

**Comment by Fabi** [comment]
You are not the author

**Comment by HerokDeV** [comment]
I know I'm not the author I was just carrying this TC to help

**Comment by HerokDeV** [comment]
I have already changed the title of carrying of TC

**Comment by Fabi** [comment]
Don't PR stuff without proper author (commit link info). Just "from Tc" is not enough.

**Comment by HerokDeV** [comment]
then what do you arise

**Comment by JBurlison** [comment]
Forged would gladly accept this PR https://github.com/ForgedWoW/ForgedCore

**Comment by Fabi** [comment]
> then what do you arise

Just like in hondas commits. As link the tc commit for that inside the commit message on github

**Pull request closed without merging**
