### PR TITLE
Fix parsing floats

### PR DESCRIPTION
**Pull request by LuigiElleBalotta**
The bug was:

//             x,           y,          z,       mapid
.go xyz 2542.36 1362.05 32.51 1220

after the parsing, i had these values:
x => 254236
y => 136205
z => 3251
mapid => 1220

the point disappeared.

This fix the issue

### CODE REVIEW

**Comment by hondacrx** [comment]
Hmm mine works fine, maybe cause your on a different language?

**Comment by LuigiElleBalotta** [comment]
It should work in every language :)

**Comment by hondacrx** [comment]
but on my test server it works fine, it tele me to the right spot

**Comment by LuigiElleBalotta** [comment]
Btw i'm using italian client with itIT dbc's (but tje worldserver crashes if the folder is called itIT and you set default locale to 11, so i had to rename the folder, but this is another issue)

**Comment by LuigiElleBalotta** [comment]
I don't know what to say, in my server it doesn't works and we don't need
to study to use the go xyz command 😂 with this fix it works, try it and if
it still works for you too then you can merge

Il 14 dic 2017 6:58 PM, "hondacrx" <notifications@github.com> ha scritto:

**Comment by hondacrx** [comment]
yeah i use enUS  so i have no way to test if it works on other languages

**Comment by LuigiElleBalotta** [comment]
Probably there is the same problem on doubles, but we'll see this more later

**Comment by Fabi** [comment]
Oh you already merged it :(

This should be done for the whole application. You can set it at server start.

**Comment by hondacrx** [comment]
@LuigiElleBalotta  can you try adding:
CultureInfo.DefaultThreadCurrentCulture = CultureInfo.InvariantCulture;
somewhere in the worldserver main method  and then remove all your fixes and test.  this would be a one line fix for all the errors with floats and doubles

**Comment by LuigiElleBalotta** [comment]
I will be back at work at 2pm, then i can try it :)

**Pull request merged**
