### PR TITLE
Fix add quest to go to Dalaran-Legion when reaching level 100

### PR DESCRIPTION
**Pull request by LuigiElleBalotta**
From ashamane core

### CODE REVIEW

**Comment by Fabi** [comment]
A unified code style should be used. Sometimes you have spaces between brackets, sometimes not. Sometimes new lines before if clauses, sometimes not. Also I think c# data types (aliases) should be used. uint instead of UInt32, etc.


About the functionality, is it tested ingame? working as expected?! Just from ashamane core is not good enough :D

**Comment by LuigiElleBalotta** [comment]
Yes tested ingame :) tomorrow i will add spaces inside brackets

Il 22 gen 2018 5:45 PM, "Fabian König" <notifications@github.com> ha
scritto:

**Comment by Fabi** [comment]
I think we are at if (…) and not if ( … ) or if( … ). Need to ask @hondacrx about stuff like that

**Comment by LuigiElleBalotta** [comment]
If( ... ) is more readable imho

Il 22 gen 2018 6:53 PM, "Fabian König" <notifications@github.com> ha
scritto:

I think we are at if (…) and not if ( … ) or if( … ). Need to ask @hondacrx
<https://github.com/hondacrx> about stuff like that

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/CypherCore/CypherCore/pull/14#issuecomment-359508298>,
or mute the thread

**Comment by hondacrx** [comment]
there is some hack fixes in there. Plus the db doesn't have any spawns out in legion yet, so no need to go there.

**Pull request closed without merging**
